AppDev-main/ViewModels/CheckoutViewModel.cs
using AppDev.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace AppDev.ViewModels
{
    public class CheckoutViewModel
    {
        [ValidateNever]
        public IEnumerable<Order> Orders { get; set; } = null!;

        [Display(Name = "Shipping Address")]
        [StringLength(255)]
        public string Address { get; set; } = null!;

        [Display(Name = "Full Name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;

        [Display(Name = "Phone Number")]
        [StringLength(20)]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; } = null!;
    }
}

AppDev-main/Controllers/BooksController.cs
using AppDev.Data;
using AppDev.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppDev.Controllers;

public class BooksController : Controller
{
    private readonly ApplicationDbContext _context;

    public BooksController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: Books
    public async Task<IActionResult> Index(SearchViewModel? model)
    {
        var query = _context.Books
            .Include(b => b.Category)
            .Include(b => b.Author)
            .Include(b => b.Image)
            .AsQueryable();

        if (model != null && !string.IsNullOrWhiteSpace(model.KeyWord))
        {
            var keyword = model.KeyWord.Trim().ToLower();
            query = query.Where(b => b.Title.ToLower().Contains(keyword)
                || b.Category.Name.ToLower().Contains(keyword));
        }

        return View(await query.ToListAsync());
    }

    // GET: Books/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Books == null)
        {
            return NotFound();
        }

        var book = await _context.Books
            .Include(b => b.Category)
            .Include(b=>b.Author)
            .Include(b => b.Store)
            .Include(b => b.Image)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }
}

AppDev-main/Controllers/CartController.cs
using AppDev.Data;
using AppDev.Models;
using AppDev.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppDev.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public CartController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        private string? _customerId;

        private string CustomerId
        {
            get
            {
                _customerId ??= userManager.GetUserId(User);
                return _customerId;
            }
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var items = await context.CartItems
                .Include(ci => ci.Book)
                .Where(ci => ci.CustomerId == CustomerId)
                .ToListAsync();
            return View(items);
        }

        // GET: Carts/Create
        public async Task<IActionResult> AddItem(int? bookId, int quantity = 1)
        {
            if (bookId == null || quantity <= 0)
                return BadRequest();

            var book = await context.Books.FindAsync(bookId);

            if (book == null)
                return BadRequest();

            var item = await context.CartItems
                .FirstOrDefaultAsync(ci => ci.CustomerId == CustomerId && ci.BookId == book.Id);

            if (item == null)
            {
                item = new()
                {
                    CustomerId = CustomerId,
                    BookId = book.Id,
                    Quantity = quantity,
                };
                context.CartItems.Add(item);
            }
            else
            {
                item.Quantity += quantity;
            }

            await context.SaveChangesAsync();

            return Ok(item);
        }

        public async Task<IActionResult> Checkout()
        {
            var customer = await userManager.GetUserAsync(User);

            if (customer == null)
                return Unauthorized();

            var orders = await context.CartItems
                .Include(ci => ci.Book)
                .Where(ci => ci.CustomerId == customer.Id)
                .GroupBy(ci => ci.Book.StoreId)
                .Select(g => new Order(CustomerId, g.Key, g.ToList()))
                .ToListAsync();

            foreach (var order in orders)
            {
                order.Store = await context.Stores
                .AsNoTracking()
                .FirstAsync(s => s.Id == order.StoreId);
            };

            var model = new CheckoutViewModel()
            {
                Orders = orders,
                Name = customer.FullName,
                Address = customer.HomeAddress,
                PhoneNumber = customer.PhoneNumber,
            };

            return View(model);
        }

        [HttpPost, ActionName("Checkout")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckoutConfirm(CheckoutViewModel model)
        {
            var customer = await userManager.GetUserAsync(User);
            if (customer == null)
                return Unauthorized();

            List<Order> orders;
            if (!ModelState.IsValid)
            {
                orders = await context.CartItems
                    .Include(ci => ci.Book)
                    .Where(ci => ci.CustomerId == customer.Id)
                    .GroupBy(ci => ci.Book.StoreId)
                    .Select(g => new Order(customer.Id, g.Key, g.ToList()))
                    .ToListAsync();

                foreach (var order in orders)
                {
                    order.Store = await context.Stores
                    .AsNoTracking()
                    .FirstAsync(s => s.Id == order.StoreId);
                };

                model.Orders = orders;

                return View(model);
            }

            var items = await context.CartItems
                .Include(ci => ci.Book)
                .Where(ci => ci.CustomerId == customer.Id)
                .ToListAsync();

            orders = items.GroupBy(ci => ci.Book.StoreId, (storeId, items) => new Order(customer.Id, storeId, items)
            {
                FullName = model.Name,
                Address = model.Address,
                PhoneNumber = model.PhoneNumber,
            })
                .ToList();

            context.CartItems.RemoveRange(items);
            context.AddRange(orders);

            await context.SaveChangesAsync();

            return View("CheckoutSuccess");
        }

        public async Task<IActionResult> RemoveItem(int? bookId, int? quantity)
        {
            if (bookId == null || quantity <= 0)
                return BadRequest();

            var item = await context.CartItems
                .FirstOrDefaultAsync(ci => ci.CustomerId == CustomerId && ci.BookId == bookId);

            if (item == null)
                return Ok();

            if (quantity == null)
            {
                context.CartItems.Remove(item);
            }
            else
            {
                if (item.Quantity > quantity)
                    item.Quantity -= quantity.Value;
                else item.Quantity = 1;
            }
            await context.SaveChangesAsync();

            return Ok(item);
        }
    }
}

AppDev-main/Controllers/OrdersController.cs
using AppDev.Data;
using AppDev.Helpers;
using AppDev.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppDev.Controllers
{
    [Authorize(Roles = Roles.User)]
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        private string? _customerId;

        private string CustomerId
        {
            get
            {
                _customerId ??= userManager.GetUserId(User);
                return _customerId;
            }
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var orders = await context.Orders
                .Include(o => o.Store)
                .Where(o => o.CustomerId == CustomerId)
                .ToListAsync();
            return View(orders);
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await context.Orders
                .Include(o => o.Store)
                .Include(o => o.OrderItems)
                .ThenInclude(oi => oi.Book)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (order == null || order.CustomerId != CustomerId)
            {
                return NotFound();
            }

            order.Customer = await userManager.FindByIdAsync(CustomerId);

            return View(order);
        }
    }
}

AppDev-main/Views/Cart/Checkout.cshtml
@model CheckoutViewModel

@{
    ViewData["Title"] = "Checkout";
}
<div class="text-center">
    <h1>Checkout</h1>
</div>
@if (Model.Orders.Count() == 0)
{
    <div class="text-center">
        <p class="text-black">Your cart is emply, please add things to cart before checking out.</p>
        <a class="btn btn-primary" asp-action="Index" asp-controller="Books">Continue to browser</a>
    </div>
}
else
{
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-7 my-3">
            <h4>Orders</h4>
            @foreach (var order in Model.Orders)
            {
                <table class="table table-hover caption-top">
                    <caption class="h5">@order.Store.Name</caption>
                    <thead>
                        <tr>
                            <th scope="auto">
                                Book Title
                            </th>
                            <th scope="col">
                                Quantity
                            </th>
                            <th scope="col">
                                Price
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in order.OrderItems)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Book.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    $@(item.Price * item.Quantity)
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th scope="col" colspan="2">
                                Total Price
                            </th>
                            <th scope="col">
                                @Html.DisplayFor(modelItem => order.TotalPrice)
                            </th>
                        </tr>
                    </tfoot>
                </table>
            }
        </div>
        <div class="col-lg-4 col-md-5 my-3">
            <form method="post">
                <h4>Shipping infomation</h4>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="my-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="my-3">
                    <label asp-for="Address" class="form-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="my-3">
                    <label asp-for="PhoneNumber" class="form-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <hr class="my4" />
                <h5 class="mb-3">Payment</h5>
                <div class="my-3">
                    <div class="form-check">
                        <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required="">
                        <label class="form-check-label" for="debit">Cash on delivery</label>
                    </div>
                    <div class="form-check">
                        <input id="credit" name="paymentMethod" type="radio" class="form-check-input" required="">
                        <label class="form-check-label" for="credit">Credit card</label>
                    </div>
                    <div class="form-check">
                        <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
                        <label class="form-check-label" for="paypal">PayPal</label>
                    </div>
                </div>
                <input type="submit" value="Process" class="btn btn-primary" />
            </form>
        </div>
    </div>
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AppDev-main/Views/Cart/CheckoutSuccess.cshtml
@{
    ViewData["Title"] = "Checkout Success";
}

<div class="text-center">
    <h1>Checkout Success</h1>
    <br class="m-3" />
    <p class="text-black my-3">Your orders are ready, please checking the Orders or go back to browser more.</p>
    <a class="btn btn-primary my-3" asp-action="Index" asp-controller="Orders">Check Orders</a>
    <a class="btn btn-secondary my-3" asp-action="Index" asp-controller="Books">Continue to browser</a>
</div>

AppDev-main/Views/Cart/Index.cshtml
@model IEnumerable<AppDev.Models.CartItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Cart</h1>

<p>
    <a asp-action="Checkout" class="btn btn-primary">Checkout</a>
</p>
<table class="table">
    <thead>
        <tr>

            <th>
                Book Title
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.Price)
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    <a asp-action="Details" asp-controller="Books" asp-route-id="@item.BookId" class="text-decoration-none text-black">
                        @Html.DisplayFor(modelItem => item.Book.Title)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Book.Price)
                </td>
                <td>
                    $@(item.Book.Price * item.Quantity)
                </td>
            </tr>
        }
    </tbody>
</table>